# Generated by Django 3.0.3 on 2020-03-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheKathmanduPostScrapeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1500)),
                ('link', models.URLField(max_length=15000)),
                ('description', models.TextField(max_length=15000)),
                ('thumbnail', models.URLField(max_length=15000)),
            ],
        ),
    ]
