# Generated by Django 3.0.3 on 2020-03-20 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thekathmandupostscrapemodel',
            name='crawled_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
